/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Models/Spaceship.glb src/Spaceship.jsx 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const GLTF_LOADER = "Models/Spaceship.glb";
export function Spaceship(props) {
  const { nodes, materials } = useGLTF(GLTF_LOADER);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Spaceship_BarbaraTheBee.geometry}
        material={materials.Atlas}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload(GLTF_LOADER);
